version: '3.0'

services:
  gcs_emulator:
    image: fsouza/fake-gcs-server
    command: -scheme http

  pubsub_emulator:
    build:
      context: .
      dockerfile: pubsub.Dockerfile
    environment:
      PORT: 4442
      PUBSUB_PROJECT_ID: test

  firestore_emulator:
    build:
      context: .
      dockerfile: firestore.Dockerfile
    environment:
      FIRESTORE_PROJECT_ID: test
      PORT: 8081

  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: dynamodb
      AWS_DEFAULT_REGION: us-west-2

  test:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile
      target: test
    image: bavard-ml-utils:test
    depends_on:
      - gcs_emulator
      - pubsub_emulator
      - firestore_emulator
      - localstack
    environment:
      STORAGE_EMULATOR_HOST: http://gcs_emulator:4443
      FIRESTORE_EMULATOR_HOST: firestore_emulator:8081
      PUBSUB_EMULATOR_HOST: pubsub_emulator:4442
      AWS_ENDPOINT: http://localstack:4566
      PUBSUB_PROJECT_ID: test
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
